// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mc2.CrudTest.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Customer Manager via API")]
    public partial class CustomerManagerViaAPIFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "CustomerApiManager.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Customer Manager via API", "As a an operator I wish to be able to Create, Update, Delete customers and list a" +
                    "ll customers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create, Update, Delete customers and list all customers via API")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void CreateUpdateDeleteCustomersAndListAllCustomersViaAPI()
        {
            string[] tagsOfScenario = new string[] {
                    "mytag"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create, Update, Delete customers and list all customers via API", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table1.AddRow(new string[] {
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi@gmail.com",
                            "123",
                            "1990-08-23",
                            "NL91ABNA0417164300"});
#line 7
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table1, "Given ");
#line hidden
#line 10
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
    testRunner.Then("via API an error message should be shown indicating \"Invalid phone number\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table2.AddRow(new string[] {
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi@gmail.com",
                            "+12124567890",
                            "1990-08-23",
                            "132164555645465"});
#line 13
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table2, "Given ");
#line hidden
#line 16
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
    testRunner.Then("via API an error message should be shown indicating \"Invalid Bank account format\"" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table3.AddRow(new string[] {
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi",
                            "+12124567890",
                            "1990-08-23",
                            "NL91ABNA0417164300"});
#line 19
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table3, "Given ");
#line hidden
#line 22
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
    testRunner.Then("via API an error message should be shown indicating \"Invalid email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table4.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi@gmail.com",
                            "+12124567890",
                            "1990-08-23",
                            "NL91ABNA0417164300"});
#line 24
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table4, "Given ");
#line hidden
#line 27
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
    testRunner.Then("via API the customer should be added successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table5.AddRow(new string[] {
                            "Ahmad2",
                            "Aghamohammadi2",
                            "ahmad.aghamohammadi2@gmail.com",
                            "+12124567892",
                            "1990-08-24",
                            "NL91ABNA0417164300"});
#line 29
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table5, "Given ");
#line hidden
#line 32
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
    testRunner.Then("via API the customer should be added successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table6.AddRow(new string[] {
                            "Ahmad3",
                            "Aghamohammadi3",
                            "ahmad.aghamohammadi@gmail.com",
                            "+12124567890",
                            "1990-08-11",
                            "NL91ABNA0417164300"});
#line 35
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table6, "Given ");
#line hidden
#line 38
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
    testRunner.Then("via API an error message should be shown indicating \"Email already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table7.AddRow(new string[] {
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi@gmail.com",
                            "+12124567890",
                            "1990-08-23",
                            "NL91ABNA0417164300"});
#line 41
    testRunner.Given("via API a new customer with the following details", ((string)(null)), table7, "Given ");
#line hidden
#line 44
    testRunner.When("via API the operator attempts to create the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
    testRunner.Then("via API an error message should be shown indicating \"Customer with the same name " +
                        "and date of birth already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table8.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi@gmail.com",
                            "123",
                            "1990-08-23",
                            "NL91ABNA0417164300"});
#line 51
    testRunner.Given("via API update customer with the following details", ((string)(null)), table8, "Given ");
#line hidden
#line 54
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
    testRunner.Then("via API an error message should be shown indicating \"Invalid phone number\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table9.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi@gmail.com",
                            "+12124567890",
                            "1990-08-23",
                            "132164555645465"});
#line 57
    testRunner.Given("via API update customer with the following details", ((string)(null)), table9, "Given ");
#line hidden
#line 60
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
    testRunner.Then("via API an error message should be shown indicating \"Invalid Bank account format\"" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table10.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "Ahmad",
                            "Aghamohammadi",
                            "ahmad.aghamohammadi",
                            "+12124567890",
                            "1990-08-23",
                            "NL91ABNA0417164300"});
#line 63
    testRunner.Given("via API update customer with the following details", ((string)(null)), table10, "Given ");
#line hidden
#line 66
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 67
    testRunner.Then("via API an error message should be shown indicating \"Invalid email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table11.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "AhmadEdited",
                            "AghamohammadiEdited",
                            "ahmad.aghamohammadiEdited@gmail.com",
                            "+12124567896",
                            "1990-08-26",
                            "NL91ABNA0417164300"});
#line 68
    testRunner.Given("via API update customer with the following details", ((string)(null)), table11, "Given ");
#line hidden
#line 71
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 72
    testRunner.Then("via API the customer should be updated successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table12.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "AhmadEdited",
                            "AghamohammadiEdited",
                            "ahmad.aghamohammadi2@gmail.com",
                            "+12124567896",
                            "1990-08-26",
                            "NL91ABNA0417164300"});
#line 74
    testRunner.Given("via API update customer with the following details", ((string)(null)), table12, "Given ");
#line hidden
#line 77
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 78
    testRunner.Then("via API an error message should be shown indicating \"Email already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table13.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "Ahmad2",
                            "Aghamohammadi2",
                            "ahmad2.aghamohammadi44@gmail.com",
                            "+12124567890",
                            "1990-08-24",
                            "NL91ABNA0417164300"});
#line 80
    testRunner.Given("via API update customer with the following details", ((string)(null)), table13, "Given ");
#line hidden
#line 83
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 84
    testRunner.Then("via API an error message should be shown indicating \"Customer with the same name " +
                        "and date of birth already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "Email",
                            "PhoneNumber",
                            "DateOfBirth",
                            "BankAccountNumber"});
                table14.AddRow(new string[] {
                            "51a9d76c-b28e-4659-aad5-965515e15e16",
                            "Ahmad2",
                            "Aghamohammadi2",
                            "ahmad2.aghamohammadi44@gmail.com",
                            "+12124567890",
                            "1990-08-24",
                            "NL91ABNA0417164300"});
#line 86
    testRunner.Given("via API update customer with the following details", ((string)(null)), table14, "Given ");
#line hidden
#line 89
    testRunner.When("via API the operator attempts to update the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 90
    testRunner.Then("via API an error message should be shown indicating \"Customer with the same name " +
                        "and date of birth already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
    testRunner.When("via API the operator lists the customers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 95
    testRunner.Then("via API the customer list should be shown successfully with 2 items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 97
    testRunner.Given("via API a customer with Id \"51a9d76c-b28e-4659-aad5-965515e15e16\" exists in the s" +
                        "ystem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 98
    testRunner.When("via API the operator deletes the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
    testRunner.When("via API the operator lists the customers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 100
    testRunner.Then("via API the customer list should be shown successfully with 1 items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
